name: ecohub
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  lottie:
  http:
  intl:
  cupertino_icons: ^1.0.6

  image_picker: ^0.8.9
  shared_preferences: ^2.2.3

  firebase_core: ^3.1.0
  firebase_auth: ^5.1.0
  cloud_firestore: ^5.0.1
  google_sign_in: ^6.2.1
  dio: ^5.4.3+1
  awesome_dialog: ^3.2.1
  flutter_spinkit: ^5.2.1
  animated_text_kit: ^4.2.2
  flutter_tflite: ^1.0.1
  smooth_page_indicator: ^1.1.0
  url_launcher: ^6.3.0
  geolocator: ^12.0.0
  geocoding: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.2

flutter:

  uses-material-design: true
  assets:
   - assets/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
