// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDAmxjcTecM2-Bz9l73ijDzvN0mVsH1EmY',
    appId: '1:458283838700:web:ac9d34f9e49abf01d4c9c9',
    messagingSenderId: '458283838700',
    projectId: 'ecohub-332a8',
    authDomain: 'ecohub-332a8.firebaseapp.com',
    storageBucket: 'ecohub-332a8.appspot.com',
    measurementId: 'G-HZ8EDHW0FW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCKaS0-AqcSVERWyXn1yvjVqnxl3bxiUw4',
    appId: '1:458283838700:android:580b60019826b5c8d4c9c9',
    messagingSenderId: '458283838700',
    projectId: 'ecohub-332a8',
    storageBucket: 'ecohub-332a8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDXvfhsrmZSzkDz7OKALfMkLQdDBdiwjqY',
    appId: '1:458283838700:ios:8d03a62a04a01fe7d4c9c9',
    messagingSenderId: '458283838700',
    projectId: 'ecohub-332a8',
    storageBucket: 'ecohub-332a8.appspot.com',
    iosBundleId: 'com.example.ecohub',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDXvfhsrmZSzkDz7OKALfMkLQdDBdiwjqY',
    appId: '1:458283838700:ios:8d03a62a04a01fe7d4c9c9',
    messagingSenderId: '458283838700',
    projectId: 'ecohub-332a8',
    storageBucket: 'ecohub-332a8.appspot.com',
    iosBundleId: 'com.example.ecohub',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDAmxjcTecM2-Bz9l73ijDzvN0mVsH1EmY',
    appId: '1:458283838700:web:1cbe94669bdc5bd1d4c9c9',
    messagingSenderId: '458283838700',
    projectId: 'ecohub-332a8',
    authDomain: 'ecohub-332a8.firebaseapp.com',
    storageBucket: 'ecohub-332a8.appspot.com',
    measurementId: 'G-HQEG335J03',
  );
}
